/**
 * The PRISM wide-report column contract — 97 columns, two header rows.
 *
 * Copied verbatim from a real vendor export so a converted file lands on an
 * identical contract. Eight columns are deliberately blank: they are the
 * spacers the report writer puts between groups, and dropping them would
 * shift every later column.
 *
 * Header text only. No candidate data.
 */
export const PRISM_WIDE_GROUP_ROW: readonly string[] = [
  "Candidate",
  "Behavior Preferences",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "Work Aptitudes",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "Core Traits",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "Mental Toughness",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "Emotional Intelligence",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "Work Preference Profile",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "PRISM Career Development Analysis",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "",
  "The Big Five report",
  "",
  "",
  "",
  "",
];

export const PRISM_WIDE_DIM_ROW: readonly string[] = [
  "",
  "Innovating",
  "Initiating",
  "Supporting",
  "Coordinating",
  "Focusing",
  "Delivering",
  "Finishing",
  "Evaluating",
  "Introversion",
  "Extroversion",
  "",
  "Practical and mechanical",
  "Investigative and analytical",
  "Creative and artistic",
  "Social and empathetic",
  "Competitive and entrepreneurial",
  "Orderly and efficient",
  "Mathematical and logical",
  "Outgoing and expressive",
  "",
  "Relationship management",
  "Emotional stability",
  "Decisiveness",
  "Self-motivation",
  "Conscientiousness",
  "Flexibility",
  "",
  "SD",
  "Skew",
  "",
  "Self Belief",
  "Ambition",
  "Resilience",
  "Self Management",
  "Optimism",
  "Determination",
  "Independence",
  "Competitiveness",
  "Adaptability",
  "Overall Mental Toughness Rating",
  "",
  "Self awareness",
  "Self management",
  "Self motivation",
  "Awareness of others",
  "Influencing others",
  "Decisiveness",
  "Consistency",
  "Relationship management",
  "",
  "Being cautious, but not fearful.  Making careful, well thought out, astute decisions.",
  "A tendency to be calm, stable and unflustered and to have a strong preference for being rational and rather impervious to stress and environmental pressures.",
  "Comfortable working independently to achieve tough objectives or tight deadlines. Working in an environment that is results-driven, physically challenging and fast-paced.",
  "Being able to concentrate for long periods on large quantities of complex information. Paying close attention to rules, instructions or detailed specifications.",
  "Building group consensus and making good use of others\u2019 talents. Consulting and enabling others to take part in the decision making process.",
  "Creating imaginative and innovative concepts, or visualising outcomes or solutions.",
  "Likely to be able to adapt to a range of situations and to tolerate both criticism and challenge. Also likely to be able to maintain consistent performance in a wide range of situations and when under considerable pressure.",
  "Being cheerful, talkative and outgoing with strangers. Having a strong need to interact socially with others for most of the time.",
  "Taking and implementing tough, unpopular decisions despite strong opposition. Confronting or challenging others in a forthright or provocative manner.",
  "A tendency to be sympathetic, co-operative and considerate, and have a strong preference for deferring to others and for relating to them by being tolerant and accommodating.",
  "A tendency to be independent, forthright and demanding, and to have a strong preference for relating to others by being tough, distant and persistent.",
  "Likely to have a high level of motivation and to show high levels of commitment to long-term goals and results which are pursued in the face of obstacles and setbacks.",
  "Likely to be effective in persuading others to change their viewpoint or to adopt your interpretation of a situation, or the need for action.",
  "",
  "Initiative",
  "Energy level",
  "Ambition",
  "Control",
  "Adaptability",
  "Risk taking",
  "Task focus",
  "Teamworking",
  "Recognition",
  "Concern for others",
  "Consensus seeking",
  "Social skills",
  "Stability",
  "People focus",
  "Abstract thinking",
  "Analytical thinking",
  "Attention to detail",
  "Compliance",
  "Dependability",
  "Determination",
  "Stress management",
  "Self management",
  "Need for social interaction",
  "Need for stability",
  "Need to achieve",
  "Need to be right",
  "",
  "extraversion",
  "agreeableness",
  "conscientiousness",
  "emotional stability",
  "openness to experience",
];

/** Row order used by the vendor export. */
export const PRISM_WIDE_SCORE_ROWS = ["Underlying", "Adapted", "Consistent"] as const;
export type PrismScoreType = (typeof PRISM_WIDE_SCORE_ROWS)[number];
