export const ROUTES = {
  LOGIN: "/login",
  SIGNUP: "/signup",
  OTP: "/otp",
  RESET: "/reset-password",
  HOME: "/home",
  DASHBOARD: "/dashboard",
  COACHES: "/coaches",
  DOCUMENTS: "/documents",
  SETTINGS: "/settings",
  SETTINGS_PRIVACY: "/settings/privacy",
  HELP: "/help",
  FEEDBACK: "/feedback",
  ANALYTICS: "/analytics",
  MERIDIAN_CHAT: "/meridian/chat",
  PRISM_ASSESSMENT: "/prism-assessment",
  /** @deprecated Wave 2 Lane 2.A (P7.1) — moved under super-admin as `SUPER_ADMIN.AGENT_TRACE_CONSOLE`. The old path now redirects to the new one. */
  DIAGNOSTIC_CHAT: "/diagnostic-chat",
  SUPER_ADMIN: {
    BASE: "/super-admin",
    DASHBOARD: "/super-admin/dashboard",
    ORGANIZATIONS: "/super-admin/organizations",
    USERS: "/super-admin/users",
    USER_MEMORY: "/super-admin/users/:userId/memory",
    SETTINGS: "/super-admin/settings",
    PROJECT_LOG: "/super-admin/project-log",
    RLHF_TRAINING: "/super-admin/rlhf-training",
    /** @deprecated Wave 2 Lane 2.B (P2.1 / D3) — redirects to MentorManagement → Prompt tab. */
    PROMPT_BUILDER: "/super-admin/prompt-builder",
    ANALYTICS: "/super-admin/analytics",
    /** @deprecated Wave 2 Lane 2.B (P2.3 / D7) — redirects to MentorManagement → Voice tab. */
    VOICE_SETTINGS: "/super-admin/voice-settings",
    PROCESS_BUILDER: "/super-admin/process-builder",
    AGENT_TRAINER: "/super-admin/agent-trainer",
    BULK_IMPORT: "/super-admin/bulk-import",
    OBSERVABILITY: "/super-admin/observability",
    /** @deprecated Wave 2 Lane 2.B (P2.2 / D4) — redirects to MentorManagement → Protocol tab. */
    INTERACTION_PROTOCOL: "/super-admin/interaction-protocol",
    MENTOR_MANAGEMENT: "/super-admin/mentor-management",
    COST_ANALYSIS: "/super-admin/cost-analysis",
    KNOWLEDGE_BASE: "/super-admin/knowledge-base",
    KNOWLEDGE_BASE_CULTURAL: "/super-admin/knowledge-base?domain=cultural",
    /** @deprecated Wave 0.E (P5.1) — redirects to `KNOWLEDGE_BASE` with `?domain=cultural`. Prefer `KNOWLEDGE_BASE_CULTURAL`. */
    CULTURAL_CONTENT: "/super-admin/cultural-content",
    PRISM_MANAGEMENT: "/super-admin/prism-management",
    PRIVACY_COMPLIANCE: "/super-admin/privacy-compliance",
    RESEARCH: "/super-admin/research",
    RESEARCH_LIBRARY: "/super-admin/research-library",
    EXPLAINABILITY: "/super-admin/explainability",
    EXPLAINABILITY_CONVERSATION: "/super-admin/explainability/c/:sessionId",
    EXPLAINABILITY_TURN: "/super-admin/explainability/c/:sessionId/t/:turnId",
    /** Wave 2 Lane 2.A (P7.1) — formerly top-level `/diagnostic-chat`; renamed and moved under super-admin. */
    AGENT_TRACE_CONSOLE: "/super-admin/agent-trace-console",
  },
  MANAGER: {
    BASE: "/manager",
    DASHBOARD: "/manager/dashboard",
    TEAM: "/manager/team",
    HIRING: "/manager/hiring",
    CANDIDATES: "/manager/candidates",
    INTERVIEWS: "/manager/interviews",
    JOB_DNA: "/manager/job-dna",
    TRAINING: "/manager/training",
    CAREER_MGMT: "/manager/career-mgmt",
    TEAM_BUILDING: "/manager/team-building",
    LEADERSHIP: "/manager/leadership",
    PRISM_TEAM: "/manager/prism-team",
    ANALYTICS: "/manager/analytics",
    BULK_IMPORT: "/manager/bulk-import",
    SETTINGS: "/manager/settings",
    JOB_BLUEPRINT: "/manager/job-blueprint",
    INTERVIEW_PREP: "/manager/interview-prep",
    TEAM_COMPOSITION: "/manager/team-composition",
  },
  COMPANY_ADMIN: {
    BASE: "/company-admin",
    DASHBOARD: "/company-admin/dashboard",
    USERS: "/company-admin/users",
    ORGANIZATION: "/company-admin/organization",
    COSTS: "/company-admin/costs",
    PRISM_OVERVIEW: "/company-admin/prism-overview",
    ANALYTICS: "/company-admin/analytics",
    SETTINGS: "/company-admin/settings",
    BULK_IMPORT: "/company-admin/bulk-import",
    OBSERVABILITY: "/company-admin/observability",
    CULTURE: "/company-admin/culture",
  },
  PRACTITIONER: {
    BASE: "/practitioner",
    DASHBOARD: "/practitioner/dashboard",
    CLIENTS: "/practitioner/clients",
    CREDITS: "/practitioner/credits",
    PRISM_CLIENTS: "/practitioner/prism-clients",
    ANALYTICS: "/practitioner/analytics",
    SETTINGS: "/practitioner/settings",
  },
  DISTRIBUTOR: {
    BASE: "/distributor",
    DASHBOARD: "/distributor/dashboard",
    NETWORK: "/distributor/network",
    PRACTITIONERS: "/distributor/practitioners",
    CREDITS: "/distributor/credits",
    TERRITORY: "/distributor/territory",
    ANALYTICS: "/distributor/analytics",
    SETTINGS: "/distributor/settings",
  },
  ONBOARDING: {
    ONE: "/onboarding/one",
    TWO: "/onboarding/two",
    THREE: "/onboarding/three",
    FOUR: "/onboarding/four",
    FIVE: "/onboarding/five",
    WIZARD: "/onboarding/wizard",
  },
  ONBOARDING_DETAILS: {
    ONE: "/onboarding/details/one",
    TWO: "/onboarding/details/two",
  },
} as const;

export const NEXT_STEPS = {
  VERIFY_MFA: "verify_mfa",
  CREATE_PROFILE: "create_profile",
  VERIFY_EMAIL: "verify_email",
  RESEND_OTP: "resend_otp",
} as const;

export const ROUTES_MAGIC = {
  MAGIC_LOGIN: "/magic-login",
  MAGIC_VERIFY: "/magic-verify",
} as const;

export const ROLES = {
  USER: "user",
  MANAGER: "manager",
  COMPANY_ADMIN: "company-admin",
  PRACTITIONER: "practitioner",
  DISTRIBUTOR: "distributor",
  SUPER_ADMIN: "super-admin",
  /** @deprecated kept for backward compatibility with existing data */
  ADMIN: "admin",
  /** @deprecated kept for backward compatibility with existing data */
  MANAGER_ADMIN: "manager-admin",
} as const;

export const PATHS = {
  SUPER_ADMIN_PREFIX: "/super-admin",
  MANAGER_PREFIX: "/manager",
  COMPANY_ADMIN_PREFIX: "/company-admin",
  PRACTITIONER_PREFIX: "/practitioner",
  DISTRIBUTOR_PREFIX: "/distributor",
} as const;

export const STORAGE_KEYS = {
  USER_TOKEN: "auth_token",
  USER_EMAIL: "user_email",
  USER_OBJ: "auth_user_obj",
  USER_REFRESH_TOKEN: "auth_refresh_token",
  USER_ROLE: "auth_role",
  USER_ONBOARDING: "auth_onboarding_done",
  USER_PASSWORD: "user_password",
  USER_SESSION: "auth_session",
  USER_NEXT_STEP: "auth_next_step",
  UI_SIDEBAR_OPEN: "ui_sidebar_open",
  UI_ALEX_FLOATING_OPEN: "ui_alex_floating_open",
} as const;
