export const ROUTES = {
  LOGIN: "/login",
  SIGNUP: "/signup",
  OTP: "/otp",
  RESET: "/reset-password",
  HOME: "/home",
  DASHBOARD: "/dashboard",
  COACHES: "/coaches",
  DOCUMENTS: "/documents",
  SETTINGS: "/settings",
  HELP: "/help",
  FEEDBACK: "/feedback",
  ANALYTICS: "/analytics",
  MERIDIAN_CHAT: "/meridian/chat",
  PRISM_ASSESSMENT: "/prism-assessment",
  SUPER_ADMIN: {
    BASE: "/super-admin",
    DASHBOARD: "/super-admin/dashboard",
    TEAM: "/super-admin/team",
    COACHES: "/super-admin/coaches",
    ORGANIZATIONS: "/super-admin/organizations",
    USERS: "/super-admin/users",
    SETTINGS: "/super-admin/settings",
    PROJECT_LOG: "/super-admin/project-log",
    RLHF_TRAINING: "/super-admin/rlhf-training",
    PROMPT_BUILDER: "/super-admin/prompt-builder",
    AUDIT_LOG: "/super-admin/audit-log",
    ANALYTICS: "/super-admin/analytics",
    VOICE_SETTINGS: "/super-admin/voice-settings",
    PROCESS_BUILDER: "/super-admin/process-builder",
    AGENT_TRAINER: "/super-admin/agent-trainer",
    BULK_IMPORT: "/super-admin/bulk-import",
    OBSERVABILITY: "/super-admin/observability",
    INTERACTION_PROTOCOL: "/super-admin/interaction-protocol",
    MENTOR_MANAGEMENT: "/super-admin/mentor-management",
    COST_ANALYSIS: "/super-admin/cost-analysis",
  },
  MANAGER: {
    BASE: "/manager",
    DASHBOARD: "/manager/dashboard",
    TEAM: "/manager/team",
    HIRING: "/manager/hiring",
    CANDIDATES: "/manager/candidates",
    INTERVIEWS: "/manager/interviews",
    JOB_DNA: "/manager/job-dna",
    TRAINING: "/manager/training",
    CAREER_MGMT: "/manager/career-mgmt",
    TEAM_BUILDING: "/manager/team-building",
    LEADERSHIP: "/manager/leadership",
    PRISM_TEAM: "/manager/prism-team",
    ANALYTICS: "/manager/analytics",
    BULK_IMPORT: "/manager/bulk-import",
    SETTINGS: "/manager/settings",
  },
  COMPANY_ADMIN: {
    BASE: "/company-admin",
    DASHBOARD: "/company-admin/dashboard",
    USERS: "/company-admin/users",
    ORGANIZATION: "/company-admin/organization",
    COSTS: "/company-admin/costs",
    TRAINING: "/company-admin/training",
    LEADERSHIP: "/company-admin/leadership",
    PRISM_OVERVIEW: "/company-admin/prism-overview",
    ANALYTICS: "/company-admin/analytics",
    SETTINGS: "/company-admin/settings",
    BULK_IMPORT: "/company-admin/bulk-import",
    OBSERVABILITY: "/company-admin/observability",
  },
  PRACTITIONER: {
    BASE: "/practitioner",
    DASHBOARD: "/practitioner/dashboard",
    CLIENTS: "/practitioner/clients",
    CREDITS: "/practitioner/credits",
    PRISM_CLIENTS: "/practitioner/prism-clients",
    ANALYTICS: "/practitioner/analytics",
    SETTINGS: "/practitioner/settings",
  },
  DISTRIBUTOR: {
    BASE: "/distributor",
    DASHBOARD: "/distributor/dashboard",
    PRACTITIONERS: "/distributor/practitioners",
    CREDITS: "/distributor/credits",
    TERRITORY: "/distributor/territory",
    ANALYTICS: "/distributor/analytics",
    SETTINGS: "/distributor/settings",
  },
  ONBOARDING: {
    ONE: "/onboarding/one",
    TWO: "/onboarding/two",
    THREE: "/onboarding/three",
    FOUR: "/onboarding/four",
    FIVE: "/onboarding/five",
  },
  ONBOARDING_DETAILS: {
    ONE: "/onboarding/details/one",
    TWO: "/onboarding/details/two",
  },
} as const;

export const NEXT_STEPS = {
  VERIFY_MFA: "verify_mfa",
  CREATE_PROFILE: "create_profile",
  VERIFY_EMAIL: "verify_email",
  RESEND_OTP: "resend_otp",
} as const;

export const ROUTES_MAGIC = {
  MAGIC_LOGIN: "/magic-login",
  MAGIC_VERIFY: "/magic-verify",
} as const;

export const ROLES = {
  USER: "user",
  MANAGER: "manager",
  COMPANY_ADMIN: "company-admin",
  PRACTITIONER: "practitioner",
  DISTRIBUTOR: "distributor",
  SUPER_ADMIN: "super-admin",
  /** @deprecated kept for backward compatibility with existing data */
  ADMIN: "admin",
  /** @deprecated kept for backward compatibility with existing data */
  MANAGER_ADMIN: "manager-admin",
} as const;

export const PATHS = {
  SUPER_ADMIN_PREFIX: "/super-admin",
  MANAGER_PREFIX: "/manager",
  COMPANY_ADMIN_PREFIX: "/company-admin",
  PRACTITIONER_PREFIX: "/practitioner",
  DISTRIBUTOR_PREFIX: "/distributor",
} as const;

export const STORAGE_KEYS = {
  USER_TOKEN: "auth_token",
  USER_EMAIL: "user_email",
  USER_OBJ: "auth_user_obj",
  USER_REFRESH_TOKEN: "auth_refresh_token",
  USER_ROLE: "auth_role",
  USER_ONBOARDING: "auth_onboarding_done",
  USER_PASSWORD: "user_password",
  USER_SESSION: "auth_session",
  USER_NEXT_STEP: "auth_next_step",
  UI_SIDEBAR_OPEN: "ui_sidebar_open",
  UI_ALEX_FLOATING_OPEN: "ui_alex_floating_open",
} as const;
