/**
 * Interview Practice role pages — per-occupation landing pages generated by the
 * backend `app.role_pages` generator (which runs off `app.market` — BLS OEWS
 * wages when available, curated reference figures otherwise). The generated
 * JSON is bundled here as static data and rendered client-side at
 * `/interview-practice/<slug>`; regenerate with
 * `python -m scripts.build_role_pages` (agent-engine) and refresh
 * `src/data/interviewRolePages.json`.
 */
import raw from "@/data/interviewRolePages.json"

export type SalaryRange = {
  low: number
  median: number
  high: number
  source: string
  asOf: string
}

export type RoleOutlook = {
  growthPct: number
  horizonYears: number
  source: string
  asOf: string
}

export type RoleCopyBlock = { id: string; heading: string; body: string }
export type RoleFaq = { question: string; answer: string }

export type InterviewRolePage = {
  slug: string
  socCode: string
  title: string
  meta: { title: string; description: string; path: string }
  hero: { headline: string; subhead: string }
  blocks: RoleCopyBlock[]
  faqs: RoleFaq[]
  market: { salary: SalaryRange | null; outlook: RoleOutlook | null }
  jsonLd: Record<string, unknown>
}

type RolePagesData = {
  generatedFrom: string
  count: number
  pages: InterviewRolePage[]
}

const DATA = raw as RolePagesData

/** All role pages, sorted by title for stable listing. */
export const ROLE_PAGES: InterviewRolePage[] = [...DATA.pages].sort((a, b) =>
  a.title.localeCompare(b.title),
)

const BY_SLUG = new Map<string, InterviewRolePage>(ROLE_PAGES.map((p) => [p.slug, p]))

/** Lookup a role page by slug, or `undefined` if there is no page for it. */
export function getRolePageBySlug(slug: string | undefined): InterviewRolePage | undefined {
  return slug ? BY_SLUG.get(slug) : undefined
}

/**
 * A concise, honest role brief to seed the Interview Practice "Job description"
 * field when a candidate starts practicing from a role page. Built ONLY from the
 * page's real data (title, SOC code, and the attributed wage/outlook figures) —
 * no invented duties — so it gives the coach role context without fabricating.
 * The candidate can edit or expand it before starting.
 */
export function buildRoleJobDescription(page: InterviewRolePage): string {
  const parts: string[] = [`${page.title} (SOC ${page.socCode}).`]
  const s = page.market.salary
  if (s) {
    parts.push(
      `Typical annual pay ranges from $${s.low.toLocaleString("en-US")} (entry) to ` +
        `$${s.high.toLocaleString("en-US")} (experienced), with a median around ` +
        `$${s.median.toLocaleString("en-US")}.`,
    )
  }
  const o = page.market.outlook
  if (o) {
    const dir =
      o.growthPct > 0
        ? `grow about ${o.growthPct}%`
        : o.growthPct < 0
          ? `shrink about ${Math.abs(o.growthPct)}%`
          : "hold roughly flat"
    parts.push(`Employment is projected to ${dir} over about ${o.horizonYears} years.`)
  }
  return parts.join(" ")
}

/** Router-state shape passed from a role page into `/interview-practice`. */
export type PracticeRoleSeed = { roleTitle: string; jobDescription: string }

/** Compact index rows for the roles listing page. */
export const ROLE_PAGE_INDEX = ROLE_PAGES.map((p) => ({
  slug: p.slug,
  title: p.title,
  socCode: p.socCode,
  path: p.meta.path,
  hasSalary: p.market.salary !== null,
}))
