/**
 * Interview Practice role pages — per-occupation landing pages generated by the
 * backend `app.role_pages` generator (which runs off `app.market` — BLS OEWS
 * wages when available, curated reference figures otherwise). The generated
 * JSON is bundled here as static data and rendered client-side at
 * `/interview-practice/<slug>`; regenerate with
 * `python -m scripts.build_role_pages` (agent-engine) and refresh
 * `src/data/interviewRolePages.json`.
 */
import raw from "@/data/interviewRolePages.json"

export type SalaryRange = {
  low: number
  median: number
  high: number
  source: string
  asOf: string
}

export type RoleOutlook = {
  growthPct: number
  horizonYears: number
  source: string
  asOf: string
}

export type RoleCopyBlock = { id: string; heading: string; body: string }
export type RoleFaq = { question: string; answer: string }

export type InterviewRolePage = {
  slug: string
  socCode: string
  title: string
  meta: { title: string; description: string; path: string }
  hero: { headline: string; subhead: string }
  blocks: RoleCopyBlock[]
  faqs: RoleFaq[]
  market: { salary: SalaryRange | null; outlook: RoleOutlook | null }
  jsonLd: Record<string, unknown>
}

type RolePagesData = {
  generatedFrom: string
  count: number
  pages: InterviewRolePage[]
}

const DATA = raw as RolePagesData

/** All role pages, sorted by title for stable listing. */
export const ROLE_PAGES: InterviewRolePage[] = [...DATA.pages].sort((a, b) =>
  a.title.localeCompare(b.title),
)

const BY_SLUG = new Map<string, InterviewRolePage>(ROLE_PAGES.map((p) => [p.slug, p]))

/** Lookup a role page by slug, or `undefined` if there is no page for it. */
export function getRolePageBySlug(slug: string | undefined): InterviewRolePage | undefined {
  return slug ? BY_SLUG.get(slug) : undefined
}

/** Compact index rows for the roles listing page. */
export const ROLE_PAGE_INDEX = ROLE_PAGES.map((p) => ({
  slug: p.slug,
  title: p.title,
  socCode: p.socCode,
  path: p.meta.path,
  hasSalary: p.market.salary !== null,
}))
