/**
 * Exercises the real `docx` builder and reads the produced .docx back.
 *
 * Asserting against the actual document rather than a mocked builder, because
 * the thing worth guaranteeing is what an operator opens in Word — that the
 * synthetic-data notice survives into the file, and that the score tables
 * carry each scale's DEFINITION and not just its number.
 */
import JSZip from "jszip"
import { exportProfileWord } from "@/lib/exportCharacterProfile"
import type { Rubric } from "@/types/character-lab"

const saved: { name: string; blob: Blob }[] = []
jest.mock("@/lib/exportTranscript", () => ({
  downloadBlob: (name: string, blob: Blob) => saved.push({ name, blob }),
}))

const RUBRIC: Rubric = {
  notice: "FICTIONAL CHARACTER — synthetic profile generated by IG Character Lab.",
  score_types: { Underlying: "instinctive" },
  bands: [],
  groups: [
    {
      group: "Behavior Preferences",
      definition: "The eight behaviour preferences.",
      per_score_type: true,
      parts: 1,
      dimensions: [
        {
          key: "finishing",
          label: "Finishing",
          measures: "Completing and closing out; follow-through to a finished state.",
          high: "Sees things through.",
          low: "Starts more than they close.",
          is_trait: true,
        },
      ],
    },
  ],
}

/**
 * jsdom's Blob has no `arrayBuffer()`, so read it through FileReader. Changing
 * the production code to `Packer.toBuffer` to suit the test would mean testing
 * a path the browser never takes.
 */
function blobToArrayBuffer(blob: Blob): Promise<ArrayBuffer> {
  return new Promise((resolve, reject) => {
    const reader = new FileReader()
    reader.onload = () => resolve(reader.result as ArrayBuffer)
    reader.onerror = () => reject(reader.error)
    reader.readAsArrayBuffer(blob)
  })
}

async function docText(blob: Blob): Promise<string> {
  const zip = await JSZip.loadAsync(await blobToArrayBuffer(blob))
  return zip.file("word/document.xml")!.async("string")
}

describe("exportProfileWord", () => {
  beforeEach(() => { saved.length = 0 })

  it("writes a .docx named after the character", async () => {
    await exportProfileWord({
      name: "Sonny Corleone", source: "The Godfather", notice: RUBRIC.notice,
      reading: "", analysis: "", colours: [], scores: {}, evidence: {},
      rubric: RUBRIC, scoreType: "Underlying",
    })
    expect(saved).toHaveLength(1)
    expect(saved[0].name).toBe("PRISM_Character_Sonny_Corleone.docx")
  })

  it("carries the synthetic-data notice into the document", async () => {
    await exportProfileWord({
      name: "Sonny Corleone", source: "", notice: RUBRIC.notice,
      reading: "", analysis: "", colours: [], scores: {}, evidence: {},
      rubric: RUBRIC, scoreType: "Underlying",
    })
    // The file leaves the building; the caveat has to leave with it.
    expect(await docText(saved[0].blob)).toContain("FICTIONAL CHARACTER")
  })

  it("prints each scale's definition beside its score, not the label alone", async () => {
    await exportProfileWord({
      name: "Sonny", source: "", notice: RUBRIC.notice, reading: "", analysis: "",
      colours: [], scores: { finishing: { Underlying: 20 } },
      evidence: { finishing: "Loses interest once the outcome is settled." },
      rubric: RUBRIC, scoreType: "Underlying",
    })
    const xml = await docText(saved[0].blob)
    expect(xml).toContain("Finishing")
    expect(xml).toContain("follow-through to a finished state")
    expect(xml).toContain("Loses interest once the outcome is settled")
  })

  it("explains what each colour pairing measures", async () => {
    await exportProfileWord({
      name: "Sonny", source: "", notice: RUBRIC.notice, reading: "", analysis: "",
      colours: [{ quadrant_id: 4, name: "Gold", value: 19, band: "Very low" }],
      scores: {}, evidence: {}, rubric: RUBRIC, scoreType: "Underlying",
    })
    const xml = await docText(saved[0].blob)
    // "Gold 19" alone invites the reader to supply their own meaning for Gold.
    expect(xml).toContain("Finishing + Evaluating")
  })

  it("renders analysis markdown as document structure, not literal asterisks", async () => {
    await exportProfileWord({
      name: "Sonny", source: "", notice: RUBRIC.notice, reading: "",
      analysis: "## Strengths\n- **Decisive** under fire\n",
      colours: [], scores: {}, evidence: {}, rubric: RUBRIC, scoreType: "Underlying",
    })
    const xml = await docText(saved[0].blob)
    expect(xml).toContain("Strengths")
    expect(xml).toContain("Decisive")
    expect(xml).not.toContain("**Decisive**")
  })
})
